logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#        blog: WARN
#        org: WARN
#        org.hibernate.SQL: DEBUG
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mobilele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
      init:
            mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8081

mail:
  host: "localhost"
  port: 1025
  username: "mobilele@mobilele.com"
  password: ""



#spring:
#    datasource:
#        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/mobilele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
#        username: root
#        password:
#    jpa:
#        database-platform: org.hibernate.dialect.MySQLDialect
#        hibernate:

#  error:
#    include-stacktrace: always
#  error:
#    whitelabel:
#      enabled: false
#            ddl-auto: create-drop
