#logging:
#    level:
#        blog: WARN
#        org: WARN
#        org.hibernate.SQL: DEBUG
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mobilele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
        password: 12345
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true


#spring:
#    datasource:
#        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/mobilele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
#        username: root
#        password:
#    jpa:
#        database-platform: org.hibernate.dialect.MySQLDialect
#        hibernate:
#            ddl-auto: create-drop